[colors]

# Normal colors
foreground       = '#CDD6F4'
background       = '#1E1E2E'
black            = '#45475A'
blue             = '#89B4FA'
cursor           = '#F5E0DC'
cyan             = '#94E2D5'
green            = '#A6E3A1'
magenta          = '#F5C2E7'
red              = '#f38ba8'
white            = '#BAC2DE'
yellow           = '#F9E2AF'

# UI colors
tabs             = '#1E1E2E'
tabs-active      = '#B4BEFE'
selection-foreground = '#1E1E2E'
selection-background = '#F5E0DC'

# Dim colors
dim-black        = '#45475A'
dim-blue         = '#89B4FA'
dim-cyan         = '#94E2D5'
dim-foreground   = '#CDD6F4'
dim-green        = '#A6E3A1'
dim-magenta      = '#F5C2E7'
dim-red          = '#F38BA8'
dim-white        = '#BAC2DE'
dim-yellow       = '#F9E2AF'

# Light colors
light-black      = '#585B70'
light-blue       = '#89B4FA'
light-cyan       = '#94E2D5'
light-foreground = '#CDD6F4'
light-green      = '#A6E3A1'
light-magenta    = '#F5C2E7'
light-red        = '#F38BA8'
light-white      = '#A6ADC8'
light-yellow     = '#F9E2AF'
